site_name: "wasabina67-org/yt2mp3"

docs_dir: "mkdocs"

site_dir: "docs"

site_url: "https://wasabina67-org.github.io/yt2mp3/"

use_directory_urls: false

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings
